version: '3'

services:
  dev:
    container_name: rede-flex-back_end-dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./src/server.js:/server.js
    ports:
      - '2021:2020'
   

  prod:
    container_name: rede-flex-back_end-prod
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '2020:2020'
    
      




