version: '3'

services:
  dev:
    container_name: rede-flex-back_end-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ./src/server.js:/server.js
    ports:
      - '3051:3051'
   

  prod:
    container_name: rede-flex-back_end-prod
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/app
      - ./src/server.js:/server.js
    ports:
      - '3051:3051'
    
      