FROM node:16-alpine

WORKDIR /usr/app

COPY package*.json ./

RUN npm install --legacy-peer-deps --production

RUN npm install -g ts-node-dev
RUN npm install tsup -g   # Instalação global do tsup
RUN npm install typescript       # Instalação local para typescript
COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3051

CMD ["npm", "run", "start"]