FROM node:16-alpine

WORKDIR /usr/app

COPY package*.json ./

RUN npm install --legacy-peer-deps

RUN npm install -g ts-node-dev

COPY . .

RUN npx prisma generate

EXPOSE 3051

CMD ["npm", "run", "dev"]
